/**
 * Created by giscafer on 2017/5/13.
 */

export const  PROJECTS: any = [
  {
    "type": ['all','vue','nodejs'],
    "img": "1",
    "title": "Ponitor",
    "subtitle": "Vue.js1.x • ES6 • Node.js • MongoDB",
    "meta": " [ P ] rice + M [ onitor ] = Ponitor 价格监测应用",
    "description": "天猫、淘宝、京东、Apple App的商品，监控商品价格发生变动时（每天定时器），推送消息（目前是发送邮件）， 商品价格趋势分析统计等！",
    "demoUrl": "http://project.xinong.wang:18080/",
    "gitUrl": "https://github.com/giscafer/Ponitor",
  },
  {
    "type": ['all','angular','app'],
    "img": "2",
    "title": "ionic3_angular4_JD(仿京东商城)",
    "subtitle": "ionic3 • ES6 • angular4",
    "meta": " 是我使用ionic混合开发的第一个项目,同时也是与大家一起交流学习的一个项目",
    "description": "是我使用ionic混合开发的第一个项目,同时也是与大家一起交流学习的一个项目",
    "demoUrl": "",
    "gitUrl": "https://github.com/dicallc/ionic3_angular4_JD",
  },
  {
    "type": ['all','react','app'],
    "img": "3",
    "title": "RN-MEITUAN(仿美团)",
    "subtitle": "react-native • ES6",
    "meta": " 一个使用React-native完成的美团的UI例子",
    "description": "一个使用React-native完成的美团的UI例子",
    "demoUrl": "",
    "gitUrl": "https://github.com/dicallc/RN-MEITUAN",
  },
  {
    "type": ['all','angular','app'],
    "img": "4",
    "title": "Ionic_TODO",
    "subtitle": "ionic3 • ES6 • angular4",
    "meta": " ionic写的一个入门级demo",
    "description": "ionic写的一个入门级demo",
    "demoUrl": "",
    "gitUrl": "https://github.com/dicallc/Ionic_TODO",
  },
  {
    "type": ['all','angular','app'],
    "img": "6",
    "title": "ionic3_angular4_Gank",
    "subtitle": "ionic3 • ES6 • angular4",
    "meta": " 一个使用ionic3和angular4开发的妹子客户端",
    "description": "一个使用ionic3和angular4开发的妹子客户端",
    "demoUrl": "",
    "gitUrl": "https://github.com/dicallc/ionic3_angular4_Gank",
  },
  {
    "type": ['all','angular','app'],
    "img": "2",
    "title": "ionic3_angular4_p2p",
    "subtitle": "ionic3 • ES6 • angular4",
    "meta": " 使用ionic3+angular4开发百度钱包的金融的部分页面",
    "description": "使用ionic3+angular4开发百度钱包的金融的部分页面",
    "demoUrl": "",
    "gitUrl": "https://github.com/dicallc/ionic3_angular4_p2p",
  },
  {
    "type": ['all','vue.js','app'],
    "img": "5",
    "title": "Weex_News",
    "subtitle": "Vue • Weex • Es6",
    "meta": "使用weex写的一个练手的知乎日报",
    "description": "使用weex写的一个练手的知乎日报",
    "demoUrl": "",
    "gitUrl": "https://github.com/dicallc/Weex_News",
  },

];
